version: '3.3'

volumes:
  postgres-storage:

services:

  postgres:
    image: postgres:11
    container_name: postgres
    environment: 
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data/postgres
    volumes:
      - postgres-storage:/data/postgres
    ports:
      - "5432:5432"
    restart: always
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


